CREATE TABLE [Markets].[MarketProfile]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Address1] NVARCHAR(200) NOT NULL,
	[Address2] NVARCHAR(200) NULL,
	[Landmark] NVARCHAR(200) NULL,
	[Zipcode] NVARCHAR(15) NOT NULL,
	[City] NVARCHAR(100) NOT NULL,
	[State] NVARCHAR(100) NOT NULL,
	[Country] NVARCHAR(100) NOT NULL,
	[Logo] BINARY NOT NULL,

	[CreatedDate] DATETIME NULL, 
    [CreatedBy] UNIQUEIDENTIFIER NULL, 
    [ModifiedDate] DATETIME NULL, 
    [ModifiedBy] UNIQUEIDENTIFIER NULL, 
)
