CREATE TABLE [Authorization].[RolePermissions]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [RoleId] UNIQUEIDENTIFIER NOT NULL, 
    [PermissionId] UNIQUEIDENTIFIER NOT NULL
)
